### ISSUE TITLE
prototipo

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-team-project-ra#1]
[Practica 3 prototipo RA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-prototipo-de-realidad-aumentada-team-project-ra/files/10843342/Practica.3.prototipo.RA.pdf)

**Comment by Abraham890** [comment]
Calificación: 18/20

**Comment by josealfredo79** [comment]
bien hecho y revisado
